/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: b453832daa36124a10d95cef93342bb7)
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
    durableNamespaces: "Scheduler" | "Stateful" | "Chat" | "Rpc";
  }
  interface Env {
    AI: Ai;
    ASSETS: Fetcher;
    Scheduler: DurableObjectNamespace<import("./src/server").Scheduler>;
    Stateful: DurableObjectNamespace<import("./src/server").Stateful>;
    Chat: DurableObjectNamespace<import("./src/server").Chat>;
    Rpc: DurableObjectNamespace<import("./src/server").Rpc>;
    OPENAI_API_KEY: string;
  }
}
interface Env extends Cloudflare.Env {}
